# Copyright (C) 2019-2025, Lux Partners Limited. All rights reserved.
# See the file LICENSE for licensing terms.

version: 2

# ref. https://goreleaser.com/customization/build/
builds:
  - id: lpm
    main: ./main/main.go
    binary: lpm
    flags:
      - -v
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

release:
  github:
    owner: luxfi
    name: lpm
