# Copyright (C) 2019-2025, Lux Partners Limited. All rights reserved.
# See the file LICENSE for licensing terms.

name: check-license
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  check-license:
    name: check-license
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Install license check
        run: go install github.com/google/addlicense@v1.0.0
      - name: Check license
        run: addlicense -f ./LICENSE.header -check -v .
